### ISSUE TITLE
🐛 BUG: unstable_dev inspect and inspector_port appear not to work

### ISSUE THREAD

**Issue by JustinGrote** [cloudflare/wrangler2#2453]
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Windows

### Describe the Bug

```typescript
describe('UnstableDevWorker', () => {
	let worker: UnstableDevWorker
	let base: string

	beforeAll(async () => {
		worker = await unstable_dev(
			'src/worker.ts',
			{ inspect: true, inspectorPort: 39929 },
			{ disableExperimentalWarning: true }
		)
		base = 'http://' + worker.address + ':' + worker.port
	})
```

`netstat` never shows 39929 opening even when pausing the debugger or leaving a long wait in the test. This is preventing me from debugging inside of unstable_dev and makes it much less useful. I use `hono` router in front of it and tend to use that instead so I can debug inside the "worker" itself, I would like to be able to use `unstable_dev` in vscode for this however

## Success Criteria

Be able to set a breakpoint within Visual Studio code using a test in vitest with unstable_dev and have it pause on the breakpoint inside the worker when calling `fetch`

**Comment by JacobMGEvans** [comment]
If you could provide a minimal repro that would help immensely, to get to it sooner.

**Comment by penalosa** [comment]
We're going to close this for now, but feel free to comment here with a minimal reproduction and we can investigate further. It's also possible this has been fixed in recent versions of Wrangler, as `unstable_dev` is undergoing fairly active development.

**Comment by ThomasHambach** [comment]
Hi @penalosa , Commented on wrong issue before.I am actually running into the same issue. The reproduction is quite simple. This is on wrangler 3.4

```   
await unstable_dev('index.ts'), {
        port: 42000,
        local: true,
        inspectorPort: 42001,
        inspect: true,
        compatibilityDate: "2023-03-14",
        logLevel: "debug",
        experimental: {
            disableExperimentalWarning: true,
            watch: false
        }
    });
await server.start();
```

Trying to connect using devtools will not work. Running `netstat -an | findstr :42001` shows no active connections.

I am trying to see where `unstable_dev` and the regular `startServer` diverge. But perhaps you know where to look.

**Comment by JustinGrote** [comment]
As an update, using Wrangler v3 and this configuration, should work fine:
https://github.com/cloudflare/workers-sdk/discussions/4174

**Comment by JustinGrote** [comment]
@penalosa still having this issue, here is a repro:
inspectorPort does not actually open the port when requested.

## Test (vitest)
```typescript
import { describe, expect, it } from 'vitest'
import { unstable_dev } from 'wrangler'

describe('Unstable Dev No Inspector Test', () => {
	it('should open inspect on custom port', async () => {
		const worker = await unstable_dev('src/worker.ts', {
			inspect: true,
			inspectorPort: 10000,
			ip: '127.0.0.1', //Just to make sure IPv6 isn't used
		})

		console.log(worker.address)
		console.log(worker.port)
		const x = await worker.fetch('index.json')
		expect(true).toBeTruthy()
	})
})
```

![image](https://github.com/cloudflare/workerd/assets/15258962/5030a402-ec3c-4c11-b167-fb3dd31aba41)


## Notes
- wrangler dev works fine

**Comment by JustinGrote** [comment]
Fixed by: https://github.com/cloudflare/workerd/issues/1408
